---
cap-location: margin
css:  [css/layout.css, css/fix-pagedown.css, css/fonts.css]
output:
  pagedown::html_paged: 
    toc: true
    self_contained: false
toc-title: Contents
paged-footnotes: true
lot: false
lof: false
toc: true 
---

# Introduction

```{r, echo=FALSE, results='hide'}
knitr::opts_chunk$set(
  echo = FALSE, 
  comment = NA, 
  message = FALSE
)
source(here::here("r/utilities.r"))


widef <- read_ipums_micro(
  ddi = "data/pma_00079.xml",
  data = "data/pma_00079.dat.gz"
)
```

```{r, echo = FALSE}
# n = 5491 (checked with flowchart)
dat <- widef %>% 
  filter(SAMPLE_1 == 85409) %>% 
  filter(RESULTFQ_1 %in% c(1,5)) %>%
  filter(AGEHQ_1 < 49) %>% 
  filter(SURVEYWILLING_1 == 1) %>%  # 6532 women aged and agreed
  filter(RESULTHQ_2 %in% 1) %>%  # completed HQ
  filter(RESULTFQ_2 %in% 1) # completed FQ

# Target: n=5207 (final report)  
# drop du jure (usual member, slept away last night), n = 5212
dat <- dat %>% 
  filter(RESIDENT_1 != 21) %>% 
  filter(RESIDENT_2 != 21 & RESIDENT_2 != 31)

# dropping NIU in CP, we get n = 5207
knitr::opts_chunk$set(echo = TRUE)
```

<aside>
`coef` shows the estimated population proportion

`_low` and `_upp` show the lower and upper bounds of a 95% confidence interval
</aside>

```{r}
library(srvyr)

dat %>% 
  as_survey_design(weight = PANELWEIGHT) %>% 
  filter(CP_1 < 90 & CP_2 < 90) %>% 
  summarise(
    survey_mean(
      CP_1 * CP_2,
      vartype = "ci",
      level = 0.95,
      proportion = TRUE,
      prop_method = "logit"
    )
  )
```
